from collections.abc import Iterator

class Search:
    def __new__(cls, /) -> Search: ...
    def __iter__(self, /) -> Iterator[str]: ...
    def __next__(self, /) -> str: ...

class Segmenter:
    @staticmethod
    def load(fname: str) -> Segmenter: ...
    def __new__(
        cls,
        /,
        unigrams: Iterator[tuple[str, float]],
        bigrams: Iterator[tuple[tuple[str, str], float]],
    ) -> Segmenter: ...
    def dump(self, /, fname: str) -> None: ...
    def score_sentence(self, /, words: Iterator[str]) -> float: ...
    def segment(self, /, s: str, search: Search) -> float: ...
